merge

diff --git a/nwchem-dev.merge/Singularity b/nwchem-dev.merge/Singularity
--- a/nwchem-dev.merge/Singularity
+++ b/nwchem-dev.merge/Singularity
@@ -4,7 +4,7 @@ From: ubuntu_jammy.sif
 MAINTAINER  Edoardo Apra <edoardo.apra@pnnl.gov>
 
 %setup
-    ls -la  ${GITHUB_WORKSPACE} \
+    ls -la  ${GITHUB_WORKSPACE} 
      export CACHEDIR=${GITHUB_WORKSPACE}/../../../cache
      rm -f ${SINGULARITY_ROOTFS}/*.txt || true
      bash -c "if [[ -z '${FC}' ]]; then echo 'FC=gfortran ' >> ${SINGULARITY_ROOTFS}/fc.txt ; else echo 'FC is ${FC}'; echo 'FC=${FC} ' >> ${SINGULARITY_ROOTFS}/fc.txt ; fi"
@@ -75,7 +75,9 @@ fi
  apt-get -y install -y tzdata git moreutils  wget rsync  sudo ca-certificates 
  echo ca_certificate=/etc/ssl/certs/ca-certificates.crt >  ~/.wgetrc 
  echo        "cacert=/etc/ssl/certs/ca-certificates.crt" >> ~/.curlrc 
- bash -o  pipefail -c "if [[ $(echo $FC | cut -c -8) == gfortran ]]; then apt-get -y install -y  ${FC}; fi" 
+ if [ $(echo $FC | cut -c -8) = gfortran ]; then
+     apt-get -y install -y  ${FC}
+ fi
  pwd 
  echo '@@ ls -lart ' 
  ls -lart  
@@ -86,7 +88,9 @@ fi
  echo pwd $(pwd) 
  echo 'ls nwchem' $(ls -lrta nwchem) 
  echo 'ls nwchem/src' $(ls -lrta nwchem/src) 
- bash -o  pipefail -c "if [[ ! -f nwchem/src/GNUmakefile ]]; then git clone -b $BRANCH --depth 1  https://github.com/$MYUSERNAME/nwchem.git; fi " 
+ if [ ! -f nwchem/src/GNUmakefile ]; then
+     git clone -b $BRANCH --depth 1  https://github.com/$MYUSERNAME/nwchem.git
+ fi 
  apt-get -y install -y   tar libnl-3-200 libnl-route-3-200 libgomp1 libnuma1 \
  g++ gfortran   make ssh patch   unzip perl-base file \
  python3 python3-dev cmake  unzip zip perl automake libtool autoconf flex  \
@@ -170,7 +174,7 @@ echo check ompi install
      cd .. ; rm -rf *tar*gz openmpi-* ucx-*
  fi 
 
-echo ' check ucx' \
+echo ' check ucx' 
  if [ ! -f $OMPI_DIR//bin/ucx_info ]; then echo ucx_info\ not\ found ; exit 1 ; fi 
  echo ' /opt/ompi/bin/ucx_info -v ' `/opt/ompi/bin/ucx_info -v|| true` 
  echo ' ucx Transports' `/opt/ompi/bin/ucx_info  -d |grep Transport |cut -c 19- || true` 
@@ -233,19 +237,18 @@ else
     export M_S='ARMCI_DEFAULT_SHMMAX_UBOUND=131072 '
 fi 
  echo M_S is $M_S 
- bash -o pipefail -c " \
-echo 'ls ~/' `ls -lrt ~/` \
-&& echo '222 PATH is ' `/usr/bin/env | grep PATH` \
-&& echo '111 which FC ' `which $FC` || true \
-&& mpif90 -show \
-&& echo FC is $FC \
-&& $FC -v \
-&& echo MAYBE_SYSVSHMEM is $M_S \
-&& make MAYBE_SYSVSHMEM='$M_S' FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } \
-&& FC=$FC ../contrib/getmem.nwchem 2000   \
-&& make FC=$FC install INSTALL_PREFIX=/opt/nwchem || { echo 'install Failure'; exit 1; }\
-&& grep SYSV tools/build/comex/config.log \
-&& ldd  ../bin/LINUX64/nwchem  "
+echo 'ls ~/' `ls -lrt ~/` 
+ echo '222 PATH is ' `/usr/bin/env | grep PATH` 
+ echo '111 which FC ' `which $FC` || true 
+ mpif90 -show 
+ echo FC is $FC 
+ $FC -v 
+ echo MAYBE_SYSVSHMEM is $M_S 
+ make MAYBE_SYSVSHMEM='$M_S' FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } 
+ FC=$FC ../contrib/getmem.nwchem 2000   
+ make FC=$FC install INSTALL_PREFIX=/opt/nwchem || { echo 'install Failure'; exit 1; }
+ grep SYSV tools/build/comex/config.log 
+ ldd  ../bin/LINUX64/nwchem  
 if [ -f /opt/intel/oneapi/compiler/latest/env/vars.sh ]; then  
     rsync -av /opt/intel/oneapi/compiler/latest/lib/lib*.so* $OMPI_DIR/lib/.
 fi 
@@ -265,8 +268,9 @@ fi
  cd ../.. 
  du -sh nwchem 
  du -sk *|sort -n  
- bash -o pipefail -c "if [[ $FC == 'ifx' ]] || [[ $FC  == 'ifort' ]]; then \
-rm -rf ~/apps  /var/intel  l_*sh ; fi"   
+if [ $FC = "ifx" ] || [ $FC  = "ifort" ]; then 
+    rm -rf ~/apps  /var/intel  l_*sh
+fi
  ls -lrth    
   ldd  /opt/nwchem/bin/nwchem  
  du -sk *|sort -n 
