merge

diff --git a/nwchem-dev.merge/Singularity b/nwchem-dev.merge/Singularity
--- a/nwchem-dev.merge/Singularity
+++ b/nwchem-dev.merge/Singularity
@@ -248,7 +248,7 @@ echo 'ls ~/' `ls -lrt ~/`
  echo FC is $FC 
  $FC -v 
  echo MAYBE_SYSVSHMEM is $M_S 
- make MAYBE_SYSVSHMEM='$M_S' FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } 
+ make MAYBE_SYSVSHMEM=$M_S FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } 
  FC=$FC ../contrib/getmem.nwchem 2000   
  make FC=$FC install INSTALL_PREFIX=/opt/nwchem || { echo 'install Failure'; exit 1; }
  grep SYSV tools/build/comex/config.log 
