patch for mpi3

diff --git a/nwchem-dev.merge/Singularity b/nwchem-dev.merge/Singularity
--- a/nwchem-dev.merge/Singularity
+++ b/nwchem-dev.merge/Singularity
@@ -582,7 +582,15 @@ echo 'ls ~/' `ls -lrt ~/`
  echo FC is $FC 
  $FC -v 
  echo MAYBE_SYSVSHMEM is $M_S 
- make MAYBE_SYSVSHMEM=$M_S FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } 
+ make MAYBE_SYSVSHMEM=$M_S FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; }
+ #patch GA
+ cd tools/ga-*
+ wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.merge/getacc.patch
+ patch -p1 < getacc.patch
+ cd ../build
+ make install
+ cd ../..
+ #
  FC=$FC ../contrib/getmem.nwchem 2000   
  make FC=$FC install INSTALL_PREFIX=/opt/nwchem || { echo 'install Failure'; exit 1; }
  grep SYSV tools/build/comex/config.log 
