cuda updates

diff --git a/nwchem-dev.ompi5x/Singularity b/nwchem-dev.ompi5x/Singularity
--- a/nwchem-dev.ompi5x/Singularity
+++ b/nwchem-dev.ompi5x/Singularity
@@ -130,7 +130,7 @@ export CUDA_ROOT=/usr/local/cuda-${CUDA_VERSION_MAJOR}.${CUDA_VERSION_MINOR}
 export PATH=${CUDA_ROOT}/bin:$PATH
 echo ls cudaroot/bin $(ls -lart ${CUDA_ROOT}/bin)
 export LD_LIBRARY_PATH=${CUDA_ROOT}/lib64:"$LD_LIBRARY_PATH" 
-echo "ls cuda rt available" $(ls /opt/nvidia/hpc_sdk/Linux_"$arch"/"$nverdot"/cuda/)
+echo "ls cuda rt available" $(ls ${CUDA_ROOT}/lib64/libcu*) || true
 CUDA_RUNTIME=$(nvcc --version |grep Cuda\ compilation | cut -d " " -f 5|sed -e s'/,//')
 echo gpu archs available $(nvcc --list-gpu-arch)
 echo CUDA_RUNTIME is $CUDA_RUNTIME
@@ -243,7 +243,7 @@ echo 'ls ~/' `ls -lrt ~/` \
 && echo MAYBE_SYSVSHMEM is $M_S \
 && make MAYBE_SYSVSHMEM='$M_S' FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } \
 && FC=$FC ../contrib/getmem.nwchem 2000   \
-&& make FC=$FC install INSTALL_PREFIX=/opt/nwchem \
+&& make FC=$FC install INSTALL_PREFIX=/opt/nwchem || { echo 'install Failure'; exit 1; }\
 && grep SYSV tools/build/comex/config.log \
 && ldd  ../bin/LINUX64/nwchem  "\
 && if [ -f /opt/intel/oneapi/compiler/latest/env/vars.sh ]; then  \
