GA_BRANCH=feature/malloc for dev

diff --git a/nwchem-dev.ompi41x.ifx/Singularity b/nwchem-dev.ompi41x.ifx/Singularity
--- a/nwchem-dev.ompi41x.ifx/Singularity
+++ b/nwchem-dev.ompi41x.ifx/Singularity
@@ -155,8 +155,12 @@ fi	   \
 && bash -o pipefail -c "if [[ ! -f nwchem/src/GNUmakefile ]]; then git clone -b $BRANCH --depth 1  https://github.com/$MYUSERNAME/nwchem.git; fi" \
 && cd nwchem \
 && echo "output of git describe  --always " `git describe  --always` || true \
+&& pwd \
 && wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/largebasis.patch \
+&& wget https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/gt.patch \
+&& ls -l *patch \
 && patch -p1 < largebasis.patch \
+&& patch -p1 -s -N < gt.patch \
 && export NWCHEM_TOP=`pwd` \
 && echo 'ls -lrta ' $(ls -lrta) \
 && echo 'pwd ' $(pwd) \
@@ -172,13 +176,16 @@ echo 'ls ~/' `ls -lrt ~/` \
 && mpif90 -show \
 && echo FC is $FC \
 && $FC -v \
-&& make FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } \
+&& if [ "$BRANCH" = "master" ]; then
+   export GA_BRANCH=feature/malloc
+fi	   \
+&& make V=-1 FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } \
 && FC=$FC ../contrib/getmem.nwchem 2000  || true \
 && make FC=$FC install INSTALL_PREFIX=/opt/nwchem \
 && ldd  ../bin/LINUX64/nwchem  "\
 && if [ -f /root/apps/oneapi/compiler/latest/env/vars.sh ]; then  \
 rsync -av /root/apps/oneapi/compiler/latest/lib/lib*.so* $OMPI_DIR/lib/. ; fi \
-&&  rm -rf /root/apps/oneapi/  /opt/nwchem/src/tce /opt/nwchem/src/NWints/simint/libsimint_source/simint.l?_p?_d? \
+&&  rm -rf /root/apps/oneapi/  /opt/nwchem/src/tce /opt/nwchem/src/NWints/simint/libsimint_source/simint.l?_p?_d? || true \
 && DEBIAN_FRONTEND=noninteractive apt-get clean -y \
 && DEBIAN_FRONTEND=noninteractive apt-get -y install localepurge \
 && echo MANDELETE >  /etc/locale.nopurge \
