ga branch

diff --git a/nwchem-dev.ompi41x.ifx.test/Singularity b/nwchem-dev.ompi41x.ifx.test/Singularity
--- a/nwchem-dev.ompi41x.ifx.test/Singularity
+++ b/nwchem-dev.ompi41x.ifx.test/Singularity
@@ -179,7 +179,7 @@ echo 'ls ~/' `ls -lrt ~/` \
 && if [ "$BRANCH" = "master" ]; then
    export GA_BRANCH=feature/malloc
 fi	   \
-&& make FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } \
+&& make V=-1 FC=$FC -j6 || { echo 'Compilation Failure'; exit 1; } \
 && FC=$FC ../contrib/getmem.nwchem 2000  || true \
 && make FC=$FC install INSTALL_PREFIX=/opt/nwchem \
 && ldd  ../bin/LINUX64/nwchem  "\
