hpcx based container

diff --git a/nwchem-dev.ompi41x.ifx.test/Singularity b/nwchem-dev.ompi41x.ifx.test/Singularity
--- a/nwchem-dev.ompi41x.ifx.test/Singularity
+++ b/nwchem-dev.ompi41x.ifx.test/Singularity
@@ -137,31 +137,31 @@ echo pwd is $(pwd)
  echo ' === git descr == ' 
  echo "output of git describe  --always " `git describe  --always` || true 
  echo ' texas check ' \
-&& ls -lrt src/NWints/texas ||true \
-&& MYCURL2="curl -LJO "\
-&& MYCURL="wget "\
-&& $MYCURL https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/largebasis.patch \
-&& patch -p1 < largebasis.patch \
-&& $MYCURL https://raw.githubusercontent.com/nwchemgit/nwchem/7e4ea3c5cd9205572fbe42c8a86f18ada43409ec/src/NWints/simint/libsimint_source/build_simint.sh > src/NWints/simint/libsimint_source/build_simint.sh \
-&& $MYCURL https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/simint_forceg++.patch \
-&& patch -p1 < simint_forceg++.patch \
-&& export NWCHEM_TOP=`pwd` \
-&& ls -lrt \
-&& cd src \
-&& ls -lrt libext/lib || true \
-&& make nwchem_config || { echo "config Failure"; exit 1; } \
-&& echo '222 PATH is ' `/usr/bin/env | grep PATH` \
-&& echo '111 which FC ' `which $FC` || true \
-&& mpif90 -show \
-&& echo FC is $FC \
-&& $FC -v \
-&&    make SKIP_COMPILERS=1 deps_stamp  >& deps.log \
-&& tail deps.log \
-&&    make directories \
-&&    export QUICK_BUILD=1 \
-&& make FC=$FC V=0 -j6 || { echo 'Compilation Failure'; exit 1; } \
-&& unset QUICK_BUILD \
-&& FC=$FC ../contrib/getmem.nwchem 2000  || true \
+ ls -lrt src/NWints/texas ||true 
+ MYCURL2="curl -LJO "\
+ MYCURL="wget "
+ $MYCURL https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/largebasis.patch 
+ patch -p1 < largebasis.patch 
+ $MYCURL https://raw.githubusercontent.com/nwchemgit/nwchem/7e4ea3c5cd9205572fbe42c8a86f18ada43409ec/src/NWints/simint/libsimint_source/build_simint.sh > src/NWints/simint/libsimint_source/build_simint.sh 
+ $MYCURL https://raw.githubusercontent.com/edoapra/nwchem-singularity/master/nwchem-dev.ompi41x.ifx/simint_forceg++.patch 
+ patch -p1 < simint_forceg++.patch 
+export NWCHEM_TOP=`pwd` 
+ ls -lrt 
+ cd src 
+ ls -lrt libext/lib || true 
+ make nwchem_config || { echo "config Failure"; exit 1; } 
+ echo '222 PATH is ' `/usr/bin/env | grep PATH` 
+ echo '111 which FC ' `which $FC` || true 
+ mpif90 -show 
+ echo FC is $FC 
+ $FC -v 
+    make SKIP_COMPILERS=1 deps_stamp  >& deps.log 
+ tail deps.log 
+    make directories 
+    export QUICK_BUILD=1 
+ make FC=$FC V=0 -j6 || { echo 'Compilation Failure'; exit 1; } 
+ unset QUICK_BUILD 
+ FC=$FC ../contrib/getmem.nwchem 2000  || true \
 && make FC=$FC install INSTALL_PREFIX=/opt/nwchem \
 && ldd  ../bin/LINUX64/nwchem  "\
 && DEBIAN_FRONTEND=noninteractive apt-get -y install localepurge \
